#+title: Problemas de conteo
#+author: Rafael Villarroel
#+email: rafaelv@uaeh.edu.mx
#+date: 26 de septiembre de 2013

#+setupfile: opciones.org

#+beamer: \setbeamertemplate{frametitle}{}
#+beamer: \setbeamertemplate{navigation symbols}{}
#+beamer: \languagepath{spanish}

#+COLUMNS: %45ITEM %10BEAMER_env(Env) %10BEAMER_act(Act) %4BEAMER_col(Col) %8BEAMER_opt(Opt)
#+PROPERTY: BEAMER_col_ALL 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 0.0 :ETC

* Problemas

** Partidos

En el torneo de fútbol participan 18 equipos, que juegan todos contra
todos una vez. ¿Cuántos partidos se juegan en total?

** Otra repartición de frutas

¿De cuántas maneras pueden 3 personas repartirse 6 manzanas, 1 pera, 1
naranja, 1 ciruela y 1 durazno?

** Suma de varios sumandos

Hallar la suma de todos los números de 4 cifras que se obtienen
permutando los dígitos 1,2,3,4.

** Equipos

¿De cuántas maneras se pueden dividir 30 personas en 3 equipos
(iguales) de 10 personas cada uno?

** Repartición de manzanas distintas

¿De cuántas maneras se pueden repartir 10 manzanas *distintas* a 4 niños?

** Leones y tigres

Un circo tiene 5 leones y 4 tigres. ¿De cuántas maneras se puede hacer
una fila con los 9 animales si un tigre no puede ir detrás de otro
tigre? (Los leones se consideran distintos entre sí, también los tigres).

** Suma divisible entre 3

¿De cuántas maneras se pueden escoger 3 números entre el 1 y el 100,
inclusive, de modo que su suma sea divisible entre 3?

** Otro problema de fila 

Si hay 3 mexicanos, 3 estadounidenses y 3 franceses, ¿de cuántas
maneras se pueden poner en fila de modo que no haya dos compatriotas
juntos? 

** Números

¿En cuántos números de 6 cifras aparecen exactamente tres números
distintos,  ninguno de ellos igual a cero?

* COMMENT Maintenance

# Local Variables:
# org-latex-pdf-process: ("pdflatex -interaction nonstopmode -output-directory %o %f")
# eval: (set-input-method "spanish-prefix")  
# End:
